spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vcs
    username: root
    password: lian.wei
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 9005
    password: lian.wei
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  resources:
#    static-locations: /static/**,/swagger-resources/**,/webjars/**
server:
  port: 9000
  servlet:
    context-path: /api
#redis
redis:
  host: 127.0.0.1
  port: 9005
  timeout: 3
  password: lian.wei
  poolMaxTotal: 10
  poolMaxIdle: 10
  poolMaxWait: 3

#druid
#spring:
#	datasource:
#		url: jdbc:mysql://127.0.0.1:3306/miaosha?useUnicode=true&characterEncoding=utf8
#		username: root
#		password: lian.wei
#		driver-class-name: com.mysql.jdbc.Driver
#		type: com.alibaba.druid.pool.DruidDataSource
#		filters: stat
#		maxActive: 2
#		initialSize: 1
#		maxWait: 60000
#		minIdle: 1
#		timeBetweenEvictionRunsMillis: 60000
#		minEvictableIdleTimeMillis: 300000
#		validationQuery: select 'x'
#		testWileIdle: true
#		testOnBorrow: false
#		testOnReturn: false
#		poolPreparedStatements: true
#		maxOpenPreparedStatements: 20

vcs:
  htpasswd: D:\\
  baseSvnUrl: http://fjyqlw:9999/svn/
  repoBase: E:\\SVNKIT_TEST\\Repositories
  respBase: E:\\SVNKIT_TEST\\vcs\\
  tmpSub: tmp
  respSub: resp
  svnUrlPrefix: /svn/hnk
  toBeAudited: audit
  svnUserId: lian.wei
  svnPassword: lian.wei